# Generated by Django 6.0.1 on 2026-01-13 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido! Use XXX.XXX.XXX-XX')])),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$', 'Telefone inválido! Use (XX) XXXXX-XXXX')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cartao_sus', models.CharField(blank=True, max_length=18, null=True)),
                ('convenio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
