# Generated by Django 6.0.1 on 2026-01-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='convenio',
        ),
    ]
