# Generated by Django 6.0.1 on 2026-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_paciente_endereco_remove_paciente_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
