# Generated by Django 6.0.1 on 2026-01-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='escolaridade',
            field=models.CharField(choices=[('SEM_INSTRUCAO', 'Sem instrução'), ('FUNDAMENTAL_INCOMPLETO', 'Fundamental incompleto'), ('FUNDAMENTAL_COMPLETO', 'Fundamental completo'), ('MEDIO_INCOMPLETO', 'Médio incompleto'), ('MEDIO_COMPLETO', 'Médio completo'), ('SUPERIOR_INCOMPLETO', 'Superior incompleto'), ('SUPERIOR_COMPLETO', 'Superior completo'), ('POS_GRADUACAO', 'Pós-graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=models.CharField(choices=[('BRASILEIRA', 'Brasileira'), ('ARGENTINA', 'Argentina'), ('BOLIVIANA', 'Boliviana'), ('CHILENA', 'Chilena'), ('COLOMBIANA', 'Colombiana'), ('PARAGUAIA', 'Paraguaia'), ('PERUANA', 'Peruana'), ('URUGUAIA', 'Uruguaia'), ('VENEZUELANA', 'Venezuelana'), ('OUTRA', 'Outra')], default='BRASILEIRA', max_length=20),
        ),
    ]
