# Generated by Django 6.0.1 on 2026-01-15 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_alter_paciente_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 15, 19, 3, 18, 746995, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
