# Generated by Django 6.0.1 on 2026-01-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0007_paciente_criado_por_alter_paciente_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_medico', to='paciente.paciente')),
            ],
        ),
    ]
