# Generated by Django 6.0.1 on 2026-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentomedico',
            name='fila',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atendimentomedico',
            name='status',
            field=models.CharField(default='aguardando', max_length=50),
        ),
    ]
