# Generated by Django 6.0.1 on 2026-01-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('recepcao', 'Recepção'), ('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('tecnico', 'Técnico'), ('administrador', 'Administrador')], max_length=20, verbose_name='Perfil'),
        ),
    ]
