# Generated by Django 6.0.1 on 2026-01-13 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0002_remove_paciente_convenio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(max_length=20)),
                ('frequencia_cardiaca', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('saturacao', models.IntegerField()),
                ('queixa_principal', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('classificacao_risco', models.CharField(choices=[('VERMELHO', 'Vermelho - Emergência'), ('LARANJA', 'Laranja - Muito Urgente'), ('AMARELO', 'Amarelo - Urgente'), ('VERDE', 'Verde - Pouco Urgente'), ('AZUL', 'Azul - Não Urgente')], max_length=10)),
                ('data_triagem', models.DateTimeField(auto_now_add=True)),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
