# Generated by Django 6.0.1 on 2026-01-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0003_alter_triagem_enfermeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='filatriagem',
            name='status',
            field=models.CharField(choices=[('aguardando_medico', 'Aguardando Médico'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='aguardando_medico', max_length=20),
        ),
        migrations.AlterField(
            model_name='filatriagem',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
