# Generated by Django 6.0.1 on 2026-01-19 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_filatriagem_status_alter_filatriagem_data_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filatriagem',
            name='status',
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='classificacao_risco',
            field=models.CharField(blank=True, choices=[('VERMELHO', 'Vermelho'), ('AMARELO', 'Amarelo'), ('VERDE', 'Verde')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='frequencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='queixa_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='saturacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='filatriagem',
            name='tempo_espera',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filatriagem',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
